### PR TITLE
Guard against record's without http

### LINKED ISSUE #16: AttributeError: 'NoneType' object has no attribute 'protocol'
While using cdxj-indexer to index a backlog of WARC data I ran into this error when using `--post-append`:

```
was@was-dev:~$ cdxj-indexer --sort --post-append /web-archiving-stacks/data/collections/jt898xc8096/fq/567/wq/8955/ARCHIVEIT-5425-MONTHLY-JOB292430-20170430083101595-00035.warc.gz > x
Traceback (most recent call last):
  File "/opt/app/was/.local/bin/cdxj-indexer", line 8, in <module>
    sys.exit(main())
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/main.py", line 477, in main
    write_cdx_index(cmd.output, cmd.inputs, vars(cmd))
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/main.py", line 492, in write_cdx_index
    indexer.process_all()
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/main.py", line 210, in process_all
    super().process_all()
  File "/opt/app/was/.local/lib/python3.8/site-packages/warcio/indexer.py", line 33, in process_all
    self.process_one(fh, out, filename)
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/main.py", line 244, in process_one
    for record in wrap_it:
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line 49, in buffering_record_iter
    join_req_resp(req, resp, post_append, url_key_func)
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line 103, in join_req_resp
    method = req.http_headers.protocol
AttributeError: 'NoneType' object has no attribute 'protocol'
```

I tracked it down to an request record that seems to lack a body, which seems wrong, but probably shouldn't generate an error? These records came from Archive-It.

```
WARC/1.0
WARC-Type: request
WARC-Target-URI: https://img1.doubanio.com/icon/u3927203-87.jpg
WARC-Date: 2017-04-30T11:39:19Z
WARC-Concurrent-To: <urn:uuid:4ababcf0-a610-4839-9b3e-57e3f1f056e2>
WARC-Record-ID: <urn:uuid:ef603b53-b29b-412e-89c3-2bac194b9224>
Content-Length: 0
WARC-Payload-Digest: sha1:3I42H3S6NNFQ2MSVX7XZKYAYSCX5QBYJ
WARC-Block-Digest: sha1:3I42H3S6NNFQ2MSVX7XZKYAYSCX5QBYJ


```

Maybe a guard against a `req.http_headers` being `None` [here](https://github.com/webrecorder/cdxj-indexer/blob/main/cdxj_indexer/bufferiter.py#L104) would be helpful in (admittedly obscure) cases like this?

### PR DESCRIPTION
**Pull request by edsu**
This is a small commit to guard against records that lack HTTP headers. Fixes #16

PS. I tried adding my test file to `test/data` but this disturbed existing tests in a way I didn't understand I think because some of the tests index everything in the `test/data` directory? I will attach the file here in case it's useful.

[missing-http.warc.gz](https://github.com/webrecorder/cdxj-indexer/files/8882351/missing-http.warc.gz)

### CODE REVIEW

**Comment by ikreymer** [comment]
This should be good, yes, as it's likely an 'implicit' revisit record, and there's nothing to join.

Would be good to add as a test, though, just in case. Can you add the version with test and then can fix? Think they should all be working on specific files now..

**Comment by ikreymer** [comment]
Should also drop py3.6 and add 3.9, 3.10, 3.11, as 3.6 has reached end-of-life.

**Comment by edsu** [comment]
@ikreymer I added the test file to the PR but no test as of yet. Notice how the test suite breaks?

```
(cdxj-indexer) ➜  cdxj-indexer git:(missing-protocol) ✗ python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
/Users/edsummers/.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running egg_info
writing cdxj_indexer.egg-info/PKG-INFO
writing dependency_links to cdxj_indexer.egg-info/dependency_links.txt
writing entry points to cdxj_indexer.egg-info/entry_points.txt
writing requirements to cdxj_indexer.egg-info/requires.txt
writing top-level names to cdxj_indexer.egg-info/top_level.txt
reading manifest file 'cdxj_indexer.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'cdxj_indexer.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform darwin -- Python 3.10.1, pytest-7.1.2, pluggy-1.0.0 -- /Users/edsummers/.local/share/virtualenvs/cdxj-indexer-XqnMCK70/bin/python
cachedir: .pytest_cache
rootdir: /Users/edsummers/Projects/cdxj-indexer
plugins: cov-3.0.0
collected 39 items

test/test_indexer.py::TestIndexing::test_warc_cdxj PASSED                [  2%]
test/test_indexer.py::TestIndexing::test_warc_cdxj_cli_main PASSED       [  5%]
test/test_indexer.py::TestIndexing::test_warc_cdxj_with_record_digests PASSED [  7%]
test/test_indexer.py::TestIndexing::test_warc_cdxj_cli_main_with_record_digests PASSED [ 10%]
test/test_indexer.py::TestIndexing::test_warc_cdxj_sorted PASSED         [ 12%]
test/test_indexer.py::TestIndexing::test_warc_cdxj_dir_root PASSED       [ 15%]
test/test_indexer.py::TestIndexing::test_warc_cdx_11 PASSED              [ 17%]
test/test_indexer.py::TestIndexing::test_warc_cdx_9 PASSED               [ 20%]
test/test_indexer.py::TestIndexing::test_warc_cdx_11_avoid_dupe_line PASSED [ 23%]
test/test_indexer.py::TestIndexing::test_index_multiple_files PASSED     [ 25%]
test/test_indexer.py::TestIndexing::test_warc_request_only PASSED        [ 28%]
test/test_indexer.py::TestIndexing::test_warc_all_cdxj PASSED            [ 30%]
test/test_indexer.py::TestIndexing::test_arc_cdxj PASSED                 [ 33%]
test/test_indexer.py::TestIndexing::test_arc_bad_edgecase PASSED         [ 35%]
test/test_indexer.py::TestIndexing::test_warc_post_query_append PASSED   [ 38%]
test/test_indexer.py::TestIndexing::test_warc_post_query_append_multi_and_json PASSED [ 41%]
test/test_indexer.py::TestIndexing::test_warc_cdxj_compressed_1 FAILED   [ 43%]
test/test_indexer.py::TestIndexing::test_warc_cdxj_compressed_2_with_digest FAILED [ 46%]
test/test_indexer.py::TestIndexing::test_warc_index_add_custom_fields PASSED [ 48%]
test/test_indexer.py::TestIndexing::test_warc_index_custom_fields_1 PASSED [ 51%]
test/test_indexer.py::TestIndexing::test_warc_index_custom_fields_2 PASSED [ 53%]
test/test_indexer.py::TestIndexing::test_cdxj_empty PASSED               [ 56%]
test/test_indexer.py::TestIndexing::test_cdxj_middle_empty_records PASSED [ 58%]
test/test_indexer.py::test_custom_indexer PASSED                         [ 61%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_1 PASSED [ 64%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_json PASSED [ 66%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_json_top_list PASSED [ 69%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_json_lines PASSED [ 71%]
test/test_postappend.py::TestPostQueryExtract::test_put_extract_method PASSED [ 74%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_non_form_data_1 PASSED [ 76%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_non_form_data_2 PASSED [ 79%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_length_invalid_ignore PASSED [ 82%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_length_too_short PASSED [ 84%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_length_too_long PASSED [ 87%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_malformed_form_data PASSED [ 89%]
test/test_postappend.py::TestPostQueryExtract::test_post_extract_no_boundary_in_multipart_form_mimetype PASSED [ 92%]
test/test_postappend.py::TestPostQueryExtract::test_options PASSED       [ 94%]
test/test_postappend.py::TestPostQueryExtract::test_head PASSED          [ 97%]
test/test_postappend.py::TestPostQueryExtract::test_amf_parse PASSED     [100%]

=================================== FAILURES ===================================
___________________ TestIndexing.test_warc_cdxj_compressed_1 ___________________

self = <test_indexer.TestIndexing object at 0x104680a90>

        def test_warc_cdxj_compressed_1(self):
            # specify file directly
            with tempfile.TemporaryFile() as temp_fh:
                res = self.index_file(
                    "",
                    sort=True,
                    post_append=True,
                    compress=temp_fh,
                    data_out_name="comp.cdxj.gz",
                    lines=11,
                )

            exp = """\
    !meta 0 {"format": "cdxj-gzip-1.0", "filename": "%s"}
    com,example)/ 20140102000000 {"offset": 0, "length": 790}
    org,httpbin)/post?__wb_method=post&data=^&foo=bar 20140610001255 {"offset": 790, "length": 325}
    """
>           assert res == exp % "comp.cdxj.gz"
E           assert '!meta 0 {"fo...ngth": 420}\n' == '!meta 0 {"fo...ngth": 325}\n'
E               !meta 0 {"format": "cdxj-gzip-1.0", "filename": "comp.cdxj.gz"}
E             - com,example)/ 20140102000000 {"offset": 0, "length": 790}
E             - org,httpbin)/post?__wb_method=post&data=^&foo=bar 20140610001255 {"offset": 790, "length": 325}
E             + com,doubanio,img1)/icon/u3927203-87.jpg 20170430113919 {"offset": 0, "length": 825}
E             + org,httpbin)/post?__wb_method=post&another=more^data&test=some+data 20200809195334 {"offset": 825, "length": 420}

test/test_indexer.py:199: AssertionError
_____________ TestIndexing.test_warc_cdxj_compressed_2_with_digest _____________

self = <test_indexer.TestIndexing object at 0x104680d60>

    def test_warc_cdxj_compressed_2_with_digest(self):
        # specify file directly
        with tempfile.TemporaryFile() as temp_fh:
            res = self.index_file(
                "",
                sort=True,
                post_append=True,
                compress=temp_fh,
                data_out_name="comp_2.cdxj.gz",
                lines=11,
                digest_records=True,
            )

        lines = res.strip().split("\n")

        assert len(lines) == 3
        assert (
            lines[0]
            == '!meta 0 {"format": "cdxj-gzip-1.0", "filename": "comp_2.cdxj.gz"}'
        )
>       assert lines[1].startswith(
            'com,example)/ 20140102000000 {"offset": 0, "length": 1292, "digest": "sha256:'
        )
E       assert False
E        +  where False = <built-in method startswith of str object at 0x1045b74b0>('com,example)/ 20140102000000 {"offset": 0, "length": 1292, "digest": "sha256:')
E        +    where <built-in method startswith of str object at 0x1045b74b0> = 'com,doubanio,img1)/icon/u3927203-87.jpg 20170430113919 {"offset": 0, "length": 1325, "digest": "sha256:a263293781d524b107253da067c3ec38a1b6cd4acce1c0fde9a5d725ec97371f"}'.startswith

test/test_indexer.py:239: AssertionError
=============================== warnings summary ===============================
../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/handyurl.py:37
../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/handyurl.py:37
  /Users/edsummers/.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/handyurl.py:37: DeprecationWarning: invalid escape sequence '\+'

../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/handyurl.py:81
../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/handyurl.py:81
  /Users/edsummers/.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/handyurl.py:81: DeprecationWarning: invalid escape sequence '\?'

../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/URLRegexTransformer.py:31
../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/URLRegexTransformer.py:31
  /Users/edsummers/.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/URLRegexTransformer.py:31: DeprecationWarning: invalid escape sequence '\('

../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/GoogleURLCanonicalizer.py:168
../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/GoogleURLCanonicalizer.py:168
  /Users/edsummers/.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/GoogleURLCanonicalizer.py:168: DeprecationWarning: invalid escape sequence '\]'

../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/IAURLCanonicalizer.py:127
../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/IAURLCanonicalizer.py:127
  /Users/edsummers/.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/surt-0.3.1-py3.10.egg/surt/IAURLCanonicalizer.py:127: DeprecationWarning: invalid escape sequence '\d'

../../.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/Py3AMF-0.8.10-py3.10.egg/pyamf/util/__init__.py:204
  /Users/edsummers/.local/share/virtualenvs/cdxj-indexer-XqnMCK70/lib/python3.10/site-packages/Py3AMF-0.8.10-py3.10.egg/pyamf/util/__init__.py:204: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if mod_name is '':

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform darwin, python 3.10.1-final-0 ----------
Name                         Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------
cdxj_indexer/__init__.py         3      0      0      0   100%
cdxj_indexer/amf.py             55     21     26      4    62%
cdxj_indexer/bufferiter.py      80      2     32      3    96%
cdxj_indexer/main.py           276      5    128      3    98%
cdxj_indexer/postquery.py      116      8     48      2    93%
--------------------------------------------------------------
TOTAL                          530     36    234     12    92%

=========================== short test summary info ============================
FAILED test/test_indexer.py::TestIndexing::test_warc_cdxj_compressed_1 - asse...
FAILED test/test_indexer.py::TestIndexing::test_warc_cdxj_compressed_2_with_digest
================== 2 failed, 37 passed, 11 warnings in 0.72s ===================
(cdxj-indexer) ➜  cdxj-indexer git:(missing-protocol) ✗
```

**Comment by edsu** [comment]
I see what's happening now. The `test_warc_cdxj_compressed_1` and `test_warc_cdxj_compressed_2_with_digest` tests are slurping up all the WARC files in `tests/data`, and are expecting the resulting compressed index to have particular `offset` and `length` values which are disturbed by the additional file in the directory.

I can adjust these if you think these payload-less http(s) response records deserve a place in the CDXJ files. Or we could try to ensure that they aren't written at all?

**Comment by edsu** [comment]
I went with assuming that it's OK for there to be CDXJ entries for these HTTP-less response records, and adjusted the values that the tests expected. I also added a new test to make sure these types of records don't cause processing w/ `--post` to blow up. If that's not the right direction to go in let me know and I can revise.

PS. Python versions were also updated.

**Comment by ikreymer** [comment]
Thanks for tracking that down, yes, I remembered there was somewhere it was going through all WARC records but forgot where =) 
The adjustments make sense, and probably do want to have this in the CDXJ so that it can returned as an empty response rather than 404 in the replay.

**Pull request merged**
